#!/bin/bash

# Uso: ./geraGraficos.sh <executavel> <flag> <diretorio de saida>
# flag: o - otimizado

# Testa se possui argumentos
if [ $# -ne 3 ]
then
    echo "Modo de Uso: ./geraGraficos.sh <diretorio de saida>"
    exit 1
fi

# Metrica e Pontos a serem avaliados
METRICA="L2CACHE L3 ENERGY FLOPS_DP"
TAM="64 100 128 200 256 512 600 900 1024 2000 2048 3000 4000"
T="TEMPO"
CORE=3
EXEC=$1
FLAG=$2
DIR=$3
echo "performance" > /sys/devices/system/cpu/cpufreq/policy$CORE/scaling_governor

# Gera arquivo com nomes diferentes, para facilitar a criacao dos graficos
# flag o é para gerar os arquivos de entrada do programa otimizado
if [ ${FLAG} == "o" ]
then
	F1="multmatVetOTZ"
	F2="multmatMatOTZ"
else
	F1="multmatVet"
	F2="multmatMat"
fi

# Compila o programa sem os marcadores, para obter o tempo de execucao
make -B >> /dev/null

touch $F1$T.dat
touch $F2$T.dat

for p in $TAM
do
	echo -n "$p " >> $F1$T.dat
	echo -n "$p " >> $F2$T.dat
	TEMPOS=$($EXEC $p)
	echo $TEMPOS | awk '{print $1}' >> $F1$T.dat
	echo $TEMPOS | awk '{print $2}' >> $F2$T.dat
done

# Compila o programa com os marcadores do likwid, para poder obter as metricas
make -B CFLAGS="-DLIKWID_PERFMON" >> /dev/null # Máquina Pessoal
# make -B CFLAGS="-I$LIKWID_INCLUDE -DLIKWID_PERFMON" > /dev/null # DINF 

for k in $METRICA	
do
	touch $F1$k.dat
	touch $F2$k.dat
	for p in $TAM
	do
		echo -n "$p " >> $F1$k.dat
		echo -n "$p " >> $F2$k.dat
     
		likwid-perfctr -C $CORE -g $k -m $EXEC $p > $k.txt

		# Separa os dados para o group FLOPS_DP
    	if [ "$k" == "FLOPS_DP" ]
    	then
			# DINF #
        	#cat ${k}.txt | grep -i "\  DP MFLOP/s" | awk '{print $5}' | awk 'NR==1' | tr '\n' ' ' >> $F1$k.dat     
        	#cat ${k}.txt | grep -i "AVX DP MFLOP/s" | awk '{print $6}' | awk 'NR==1' >> $F1$k.dat     
        	#cat ${k}.txt | grep -i "\  DP MFLOP/s" | awk '{print $5}' | awk 'NR==2' | tr '\n' ' ' >> $F2$k.dat     
        	#cat ${k}.txt | grep -i "AVX DP MFLOP/s" | awk '{print $6}' | awk 'NR==2' >> $F2$k.dat
			# Máquina Pessoal #
			cat ${k}.txt | grep -i "\  DP \[MFLOP/s\]" | awk '{print $5}' | awk 'NR==1' | tr '\n' ' ' >> $F1$k.dat
        	cat ${k}.txt | grep -i "AVX DP \[MFLOP/s\]" | awk '{print $6}' | awk 'NR==1' >> $F1$k.dat
        	cat ${k}.txt | grep -i "\  DP \[MFLOP/s\]" | awk '{print $5}' | awk 'NR==2' | tr '\n' ' ' >> $F2$k.dat
        	cat ${k}.txt | grep -i "AVX DP \[MFLOP/s\]" | awk '{print $6}' | awk 'NR==2' >> $F2$k.dat
    	fi

    	# Separa os dados para o group ENERGY
    	if [ "$k" == "ENERGY" ]
    	then
        	cat ${k}.txt | grep -i "ENERGY \[J\]" | awk '{print $5}' | awk 'NR==1' >> $F1$k.dat # DINF     
        	cat ${k}.txt | grep -i "ENERGY \[J\]" | awk '{print $5}' | awk 'NR==2' >> $F2$k.dat # DINF     
    	fi		
		
		# Separa os dados para o group L3
    	if [ "$k" == "L3" ]
    	then
        	cat ${k}.txt| grep -i "L3 bandwidth" | awk '{print $6}' | awk 'NR==1' >> $F1$k.dat # DINF     
        	cat ${k}.txt | grep -i "L3 bandwidth" | awk '{print $6}' | awk 'NR==2' >> $F2$k.dat # DINF     
	   	fi		
		

    	if [ "$k" == "L2CACHE" ]
    	then
        	cat ${k}.txt | grep -i "L2 miss ratio" | awk '{print $6}' | awk 'NR==1' >> $F1$k.dat # DINF     
        	cat ${k}.txt | grep -i "L2 miss ratio" | awk '{print $6}' | awk 'NR==2' >> $F2$k.dat # DINF     
	   	fi		

		rm $k.txt
	done
done
echo "powersave" > /sys/devices/system/cpu/cpufreq/policy$CORE/scaling_governor

# Move arquivos para o diretório de saída
mkdir -p $DIR
mv *.dat $DIR

# Para obter topologia dos cpu's
#      likwid-topology -c -g

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter lista de Eventos e Contadores
#      likwid-perfctr -e

