#!/bin/bash

# Forma de uso:
#
#         perfctr <CORE_ID> <GRUPO_PERFORMANCE> ./matmult <opcoe_matmult>
#
# Exemplo, para fazer as medições de performance de FLOPS_DP no core 3
#
#         perfctr 3 FLOPS_DP 64 ./matmult ./matmultOtz
#


METRICA="L2CACHE L3 ENERGY FLOPS_DP"
CORE=$1
P=$2
EX1=$3
EX2=$4
echo "performance" > /sys/devices/system/cpu/cpufreq/policy$CORE/scaling_governor

    for M in ${METRICA}
    do
	    EX=${EX1}
	    echo ${M}
	    for i in {1..2}
	    do
    
	        echo ${EX}

	        likwid-perfctr -C $CORE -g $M -m $EX $P > $M.txt

	        # Separa os dados para o group FLOPS_DP
            if [ "$M" == "FLOPS_DP" ]
            then
            cat ${M}.txt | grep -i "\  DP \[MFLOP/s\]" | awk '{print $5}' | awk 'NR==1' | tr '\n' ' '
            cat ${M}.txt | grep -i "AVX DP \[MFLOP/s\]" | awk '{print $6}' | awk 'NR==1'      
            cat ${M}.txt | grep -i "\  DP \[MFLOP/s\]" | awk '{print $5}' | awk 'NR==2' | tr '\n' ' '     
            cat ${M}.txt | grep -i "AVX DP \[MFLOP/s\]" | awk '{print $6}' | awk 'NR==2'     
            fi
            # Separa os dados para o group ENERGY
            if [ "$M" == "ENERGY" ]
            then
            	cat ${M}.txt | grep -i "ENERGY \[J\]" | awk '{print $5}' | awk 'NR==1'     
            	cat ${M}.txt | grep -i "ENERGY \[J\]" | awk '{print $5}' | awk 'NR==2'     
            fi		

	        # Separa os dados para o group L3
            if [ "$M" == "L3" ]
            then
            	cat ${M}.txt| grep -i "L3 bandwidth" | awk '{print $6}' | awk 'NR==1'     
            	cat ${M}.txt | grep -i "L3 bandwidth" | awk '{print $6}' | awk 'NR==2'     
	        fi		

            if [ "$M" == "L2CACHE" ]
            then
            	cat ${M}.txt | grep -i "L2 miss ratio" | awk '{print $6}' | awk 'NR==1'
            	cat ${M}.txt | grep -i "L2 miss ratio" | awk '{print $6}' | awk 'NR==2'
	        fi		

	        EX=${EX2}
	        rm ${M}.txt
	    done
        echo
    done
echo "powersave" > /sys/devices/system/cpu/cpufreq/policy$CORE/scaling_governor

# Para obter topologia dos cpu's
#      likwid-topology -c -g

# Para obter lista de grupos de indicadores de performance:
#      likwid-perfctr -a

# Para obter lista de Eventos e Contadores
#      likwid-perfctr -e

